AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: AWS Lambda - github-project-archiver
Parameters:
    Stack:
        Description: Stack name
        Type: String
    App:
        Description: Application name
        Type: String
        Default: repo-apocalypse
    Stage:
        Description: Stage name
        Type: String
        AllowedValues:
            - PROD
            - CODE
        Default: CODE
    DeployBucket:
        Description: Bucket to download Lambda from
        Type: String
    TargetBucket:
        Description: Bucket to upload archived repositories to
        Type: String
        Default: ''
    PathPrefix:
        Type: String
        Description: Prefix to apply to filename of archive when uploading to S3 bucket
    GithubClientId:
        Type: String
    GithubClientSecret:
        Type: String
        NoEcho: true

Resources:
  Lambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName:
          !Sub repo-apocalypse-${Stage}
      CodeUri:
        Bucket: !Ref DeployBucket
        Key: !Sub ${Stack}/${Stage}/repo-apocalypse/repo-apocalypse.zip
      Description: github-project-archiver
      Handler: com.gu.repoapocalypse.Lambda::respond
      MemorySize: 512
      Runtime: java8
      Timeout: 300
      Events:
        Api:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
            RestApiId: !Ref API
      Policies:
      - Version: 2012-10-17
        Statement:
        - Effect: Allow
          Action:
          - s3:PutObject
          - s3:PutObjectAcl
          Resource: !Sub arn:aws:s3:::${TargetBucket}/*
      Environment:
        Variables:
          BUCKET_NAME: !Ref TargetBucket
          CLIENT_ID: !Ref GithubClientId
          CLIENT_SECRET: !Ref GithubClientSecret
          PATH_PREFIX: !Ref PathPrefix


  API:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref Stage
      DefinitionBody:
        swagger: 2.0
        info:
          title: !Ref AWS::StackName
        paths:
          "/{proxy+}":
            x-amazon-apigateway-any-method:
              x-amazon-apigateway-integration:
                httpMethod: POST
                type: aws_proxy
                uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${Lambda.Arn}/invocations
              responses: {}
